# Generated by Django 3.1.3 on 2021-01-04 02:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
